events {}

http {

    # REDIRECCIÓN HTTP → HTTPS
    server {
        listen 80;
        server_name comuva.com www.comuva.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # SERVIDOR HTTPS
    server {
        listen 443 ssl;
        server_name comuva.com www.comuva.com;

        ssl_certificate /etc/letsencrypt/live/comuva.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/comuva.com/privkey.pem;

        location / {
            proxy_pass http://comunidad-frontend;
        }

        location /api/ {
            proxy_pass http://comunidad-backend:3001;
        }
    }
}
