# ------------------------------
# STAGE 1: Build
# ------------------------------
FROM node:18 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# ------------------------------
# STAGE 2: Runtime
# ------------------------------
FROM node:18-alpine

WORKDIR /app
COPY --from=build /app /app

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "server.js"]