version = 5.4.0
archive_dir = /etc/letsencrypt/archive/comuva.com
cert = /etc/letsencrypt/live/comuva.com/cert.pem
privkey = /etc/letsencrypt/live/comuva.com/privkey.pem
chain = /etc/letsencrypt/live/comuva.com/chain.pem
fullchain = /etc/letsencrypt/live/comuva.com/fullchain.pem
[renewalparams]
account = f9aeec1ea87038ac970d041f4cada6f8
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
comuva.com = /var/www/certbot
www.comuva.com = /var/www/certbot
